name: mars_it_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # google fonts
  google_fonts: ^5.1.0
  # for svg files
  flutter_svg: ^2.0.10+1
  # for log message
  logger: ^2.0.1
  # toast message for user
  fluttertoast: ^8.2.2
  # for network
  dio: ^5.3.3
  # for save small data to local
  shared_preferences: ^2.2.2
  # for DI (Dependency Injection)
  get_it: ^7.6.4
  # for state management
  flutter_bloc: ^8.1.3
  # vaqtinchalik
  provider: ^6.0.5
  # for datetime parsing
  intl: ^0.19.0
  # for launching other apps
  url_launcher: ^6.0.12
  #
  permission_handler: ^11.3.1
  # path provider
  path_provider: ^2.1.3
  # for swiping cards
  flutter_slidable: ^3.1.0

  # Functional programming things
  dartz: ^0.10.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/learning_journey/
    - assets/images/emojis/